<?php
/**
 * @author  RadiusTheme
 * @since   1.0
 * @version 1.0
 */

namespace RT\FoodymatCore\Modules;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class IconList {

    public static function fontello() {
        return [
	        "icon-rt-warning-empty" => "warning",
			"icon-rt-tag" => "tag",
			"icon-rt-filter" => "filter",
	        "icon-rt-filter-2" => "filter-2",
			"icon-rt-tags" => "tags",
			"icon-rt-flower" => "flower",
	        "icon-rt-plus" => "plus",
	        "icon-rt-plus-1" => "plus-1",
	        "icon-rt-minus" => "minus",
	        "icon-rt-up-angle-bar" => "up-angle-bar",
	        "icon-rt-paper-plane" => "paper-plane",
	        "icon-rt-quote" => "quote",
	        "icon-rt-reply" => "reply",
	        "icon-rt-search" => "search",
	        "icon-rt-search-1" => "search-1",
	        "icon-rt-location-1" => "location-1",
	        "icon-rt-location-2" => "location-2",
	        "icon-rt-location-3" => "location-3",
	        "icon-rt-location-4" => "location-4",
	        "icon-rt-location-5" => "location-5",
	        "icon-rt-available-location" => "available-location",
	        "icon-rt-user" => "user",
	        "icon-rt-user-1" => "user-1",
	        "icon-rt-user-2" => "user-2",
	        "icon-rt-user-3" => "user-3",
	        "icon-rt-calendar" => "calendar",
	        "icon-rt-calender-2" => "calender-2",
	        "icon-rt-calender-3" => "calender-3",
	        "icon-rt-calender-4" => "calender-4",
	        "icon-rt-down-arrow" => "down-arrow",
	        "icon-rt-tree" => "tree",
	        "icon-rt-email" => "email",
	        "icon-rt-play" => "play",
	        "icon-rt-cart" => "cart",
	        "icon-rt-clock" => "clock",
	        "icon-rt-arrow-circle" => "arrow-circle",
	        "icon-rt-phone" => "phone",
	        "icon-rt-phone-2" => "phone-2",
	        "icon-rt-comment" => "comment",
	        "icon-rt-comment-2" => "comment-2",
	        "icon-rt-medicine" => "medicine",
	        "icon-rt-ei-user" => "ei-user",
	        "icon-rt-marketing" => "marketing",
	        "icon-rt-education" => "education",
	        "icon-rt-round-border-tick" => "round-border-tick",
	        "icon-rt-award" => "award",
	        "icon-rt-image" => "image",
	        "icon-rt-video" => "video",
	        "icon-rt-check" => "check",
	        "icon-rt-check-2" => "check-2",
	        "icon-rt-check-3" => "check",
	        "icon-rt-share" => "share",
	        "icon-rt-carbon-forum" => "carbon-forum",
	        "icon-rt-feedback" => "feedback",
	        "icon-rt-chevron-down" => "chevron-down",
	        "icon-rt-chevron-right-1" => "chevron-right-1",
	        "icon-rt-eye" => "eye",
	        "icon-rt-list" => "list",
	        "icon-rt-grid" => "grid",
	        "icon-rt-grid-2" => "grid-2",
	        "icon-rt-i" => "i",
	        "icon-rt-location-pointer" => "location-pointer",
	        "icon-rt-location-pointer-2" => "location-pointer-2",
	        "icon-rt-lock" => "lock",
	        "icon-rt-round-tick" => "round-tick",
	        "icon-rt-star" => "star",
	        "icon-rt-subscribe-email" => "subscribe-email",
	        "icon-rt-arrow-double" => "arrow-double",
	        "icon-rt-article" => "article",
	        "icon-rt-select-category" => "select-category",
	        "icon-rt-registration" => "registration",
	        "icon-rt-pdf" => "pdf",
	        "icon-rt-arrow-right-1" => "arrow-right-1",
	        "icon-rt-like" => "like",
	        "icon-rt-heart" => "heart",
	        "icon-rt-zoom-in" => "zoom-in",
	        "icon-rt-zoom-out" => "zoom-out",
	        "icon-rt-quotes-stroke" => "quotes-stroke",
	        "icon-rt-check-mark" => "check-mark",
	        "icon-rt-heart-1" => "heart-1",
	        "icon-rt-doctor" => "doctor",
	        "icon-rt-trust-badge" => "trust-badge",
	        "icon-rt-x-twitter" => "x-twitter",
	        "icon-rt-guidance-service" => "guidance-service",
	        "icon-rt-find-doctor" => "find-doctor",
	        "icon-rt-finance-feature" => "finance-feature",
	        "icon-rt-google-play" => "google-play",
	        "icon-rt-dollar-1" => "dollar-1",
	        "icon-rt-left-arrow" => "left-arrow",
			"icon-rt-right-arrow" => "right-arrow",
			"icon-rt-solar-star-fall" => "solar-star-fall",
			"icon-rt-message" => "message",
	        "icon-rt-digital-art" => "digital-art",
			"icon-rt-money-analysis-service" => "analysis-service",
			"icon-rt-quarter-circle" => "quarter-circle",
			"icon-rt-quotation-right" => "quotation-right",
			"icon-rt-quotation-right-small" => "quotation-right-small",
			"icon-rt-quotation-small" => "quotation-small",
			"icon-rt-quotation-small-alt" => "quotation-small-alt",
			"icon-rt-review" => "review",
			"icon-rt-quote-2" => "quote-2",
			"icon-rt-chevron-right" => "chevron-right",
			"icon-rt-secure-data-service" => "secure-data-service",
			"icon-rt-security-service" => "security-service",
			"icon-rt-solve-problems" => "solve-problems",
			"icon-rt-tax-service" => "tax-service",
			"icon-rt-arrow-vector" => "arrow-vector",
			"icon-rt-time-data-service" => "time-data-service",
			"icon-rt-comments" => "comments",
			"icon-rt-ui-ux-service" => "ui-ux-service",
			"icon-rt-user-datalist-feature" => "user-datalist-feature",
			"icon-rt-analysis-service" => "analysis-service",
			"icon-rt-angle-down" => "angle-down",
			"icon-rt-application-feature" => "application-feature",
			"icon-rt-apple" => "apple",
			"icon-rt-app-service" => "app-service",
			"icon-rt-app-service-alt" => "app-service-alt",
			"icon-rt-communication-service" => "communication-service",
			"icon-rt-communication-service-alt" => "communication-service-alt",
			"icon-rt-content-marketing" => "content-marketing",
			"icon-rt-correct" => "correct",
			"icon-rt-credit-feature" => "credit-feature",
			"icon-rt-data-service" => "data-service",
			"icon-rt-digital-art" => "digital-art",
			"icon-rt-development-service" => "development-service",
			"icon-rt-digital-marketing-service" => "digital-marketing-service",
			"icon-rt-download" => "download",
			"icon-rt-file" => "file",
			"icon-rt-file-alt" => "file-alt",
			"icon-rt-percentage" => "percentage",
			"icon-rt-savings-feature" => "savings-feature",
			"icon-rt-finance-consulting-feature" => "finance-consulting-feature",
			"icon-rt-facebook" => "facebook",
			"icon-rt-github-circled" => "github-circled",
			"icon-rt-pinterest-circled" => "pinterest-circled",
			"icon-rt-pinterest-squared" => "pinterest-squared",
			"icon-rt-linkedin" => "linkedin",
			"icon-rt-folder-empty" => "folder-empty",
			"icon-rt-star-half-alt" => "star-half-alt",
			"icon-rt-instagram" => "instagram",
			"icon-rt-skype" => "skype",
			"icon-rt-vimeo-squared" => "vimeo-squared",
			"icon-rt-vine" => "vine",
			"icon-rt-pinterest" => "pinterest",
			"icon-rt-whatsapp" => "whatsapp",
			"icon-rt-envelope-open-o" => "envelope-open-o",
			"icon-rt-facebook-squared" => "facebook-squared",
			"icon-rt-linkedin-squared" => "linkedin-squared",
	        "icon-rt-youtube" => "youtube",
	        "icon-rt-youtube-2" => "rt-youtube",
	        "icon-rt-youtube-play" => "youtube-play",
        ];
    }

	public static function fontello_service() {
		return [
			" " => "Icon Empty",
			"icon-rt-data-service" => "smart-data-service",
			"icon-rt-app-service" => "analysis-app-service",
			"icon-rt-security-service" => "website-security-service",
			"icon-rt-ui-ux-service" => "ui-ux-service",
			"icon-rt-digital-marketing-service" => "digital-marketing-service",
			"icon-rt-development-service" => "development-service",
			"icon-rt-digital-art" => "digital-art",
			"icon-rt-communication-service" => "communication-service",
			"icon-rt-communication-service-alt" => "communication-service-alt",
			"icon-rt-app-service-alt" => "app-service-alt",
			"icon-rt-tax-service" => "tax-service",
			"icon-rt-guidance-service" => "financial-guidance-service",
			"icon-rt-money-analysis-service" => "money-analysis-service",
			"icon-rt-finance-feature" => "analysis-finance-feature",
			"icon-rt-savings-feature" => "automatic-savings-feature",
			"icon-rt-credit-feature" => "providing-credit-feature",
			"icon-rt-analysis-service" => "analytics-service",
			"icon-rt-application-feature" => "application-feature",
			"icon-rt-finance-consulting-feature" => "finance-consulting-feature",
			"icon-rt-apple" => "apple",
			"icon-rt-dollar-1" => "dollar",
			"icon-rt-solve-problems" => "solve-problems",
			"icon-rt-content-marketing" => "content-marketing",
			"icon-rt-secure-data-service" => "secure-data-service",
			"icon-rt-time-data-service" => "time-data-service",
		];
	}
}
